README updated
sapcc/vrops-exporter pull request #194
Opened 2022-02-14 16:28 UTC by richardtief

2022-02-15 11:12 UTC, richardtief commented
@viennaa @christopherhans Please read over once, if there are any errors in it.

2022-02-17 11:10 UTC, viennaa requested changes
Thanks for tackling this long due item. I've added my remarks.

2022-02-17 11:10 UTC, viennaa commented on README.md
> +To avoid multiple implementations of functionality, the collectors follow an inheritance structure.
Path to `/atlas/netbox.json` is specific to us.

Actually just a netbox-like file is needed there. I would put in a file as input for `inventory.py` and an arrow from InventoryBuilder to that file with `<<use>>`. Reference to documentation for internal format.
Maybe some dotted line around the atlas file to indicate, that we are providing this with a service.

2022-02-17 11:10 UTC, viennaa commented on README.md
> +![](images/collectors.png)
Nice!

2022-02-17 11:10 UTC, viennaa commented on README.md
> +## Running the software
Should we move this to the top? If not, we should give it a table of contents at the beginning of this documentation.

2022-02-17 11:10 UTC, viennaa commented on README.md
> +The inventory retrieves all VMware resources by `name` and `uuid` from the vROps application interface, preserving the original parent-child relationships.         Likewise, it reads the atlas config
Isn't this duplicate information to the inventory section above?

2022-02-17 11:10 UTC, viennaa commented on README.md
>  For running this in kubernetes (like we do), you might want to have a look at our [helm chart](https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/vrops-exporter)
This should go to a dedicated section:
```Run in Kubernetes```

2022-02-17 21:41 UTC, closed without merging